{% set version = "0.0.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ttdo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ttdo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ttdo/ttdo_{{ version }}.tar.gz
  sha256: 8324a70a582c3f2c8d14a8d6db63090fd685c2ba178da661ddb705caddc7592e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
    - r-diffobj
    - r-tinysnapshot >=0.0.8
    - r-tinytest >=1.4.1
  run:
    - r-base
    - r-base64enc
    - r-diffobj
    - r-tinysnapshot >=0.0.8
    - r-tinytest >=1.4.1

test:
  commands:
    - $R -e "library('ttdo')"           # [not win]
    - "\"%R%\" -e \"library('ttdo')\""  # [win]

about:
  home: https://github.com/eddelbuettel/ttdo/, https://dirk.eddelbuettel.com/code/ttdo.html
  license: GPL-2.0-or-later
  summary: The 'tinytest' package offers a light-weight zero-dependency unit-testing framework
    to which this package adds support via the 'diffobj' package for 'diff'-style textual
    comparison of R objects, as well as via 'tinysnapshot' package for visual differences
    in plots.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: ttdo
# Title: Extend 'tinytest' with 'diffobj' and 'tinysnapshot'
# Version: 0.0.10
# Date: 2025-01-21
# Authors@R: c(person("Dirk", "Eddelbuettel", role = c("aut", "cre"), email = "edd@debian.org", comment = c(ORCID = "0000-0001-6419-907X")), person("Alton", "Barbehenn", role = "aut", comment = c(ORCID = "0009-0000-3364-7204")))
# Description: The 'tinytest' package offers a light-weight zero-dependency unit-testing framework to which this package adds support via the 'diffobj' package for 'diff'-style textual comparison of R objects, as well as via 'tinysnapshot' package for visual differences in plots.
# License: GPL (>= 2)
# URL: https://github.com/eddelbuettel/ttdo/, https://dirk.eddelbuettel.com/code/ttdo.html
# BugReports: https://github.com/eddelbuettel/ttdo/issues
# NeedsCompilation: no
# Encoding: UTF-8
# Imports: tinytest (>= 1.4.1), diffobj, tinysnapshot (>= 0.0.8), base64enc
# RoxygenNote: 7.3.2
# Packaged: 2025-01-21 15:04:32 UTC; edd
# Author: Dirk Eddelbuettel [aut, cre] (<https://orcid.org/0000-0001-6419-907X>), Alton Barbehenn [aut] (<https://orcid.org/0009-0000-3364-7204>)
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Repository: CRAN
# Date/Publication: 2025-01-21 15:40:02 UTC
